package(default_visibility = ["//visibility:public"])

cc_test(
    name = "state_record_test",
    srcs = ["state_record_test.cc"],
    deps = [
        "//state_record/deserialize:deserializer",
        "//state_record/parsers:json_parser",
        "//state_record/utils:macros",
    ],
)
